Tablas


  CREATE TABLE "BDWEB"."ADMINISTRADOR" 
   (	"ID_ADMINISTRADOR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"LOGIN" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "ADMINISTRADOR_PK" PRIMARY KEY ("ID_ADMINISTRADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE TABLE "BDWEB"."ALTURA" 
   (	"ID_ALTURA" NUMBER(6,0), 
	"TAMANO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_ALTURA" PRIMARY KEY ("ID_ALTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_ALTURA" 
  BEFORE INSERT ON altura
  FOR EACH ROW
BEGIN
  :new.id_altura := altura_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_ALTURA" ENABLE;
 

  CREATE TABLE "BDWEB"."BEBEDOR" 
   (	"ID_BEBEDOR" NUMBER(6,0), 
	"FRECUENCIA" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_BEBEDOR" PRIMARY KEY ("ID_BEBEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_BEBEDOR" 
  BEFORE INSERT ON bebedor
  FOR EACH ROW
BEGIN
  :new.id_bebedor := bebedor_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_BEBEDOR" ENABLE;
 

  CREATE TABLE "BDWEB"."CIUDAD" 
   (	"ID_CIUDAD" NUMBER(6,0), 
	"NOMBRE_CIUDAD" VARCHAR2(20 BYTE) CONSTRAINT "CIUDAD_VAR" NOT NULL ENABLE, 
	"ID_PAIS" NUMBER(6,0), 
	 CONSTRAINT "PK_CIUDAD" PRIMARY KEY ("ID_CIUDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE, 
	 CONSTRAINT "FK_PAIS" FOREIGN KEY ("ID_PAIS")
	  REFERENCES "BDWEB"."PAIS" ("ID_PAIS") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_CIUDAD" 
  BEFORE INSERT ON ciudad
  FOR EACH ROW
BEGIN
  :new.id_ciudad := ciudad_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_CIUDAD" ENABLE;
 

  CREATE TABLE "BDWEB"."CLICK" 
   (	"ID_CLICK" NUMBER(6,0), 
	"ID_CLICKER" NUMBER(6,0), 
	"ID_CLICKD" NUMBER(6,0), 
	"FECHA_DEL_CLICK" DATE DEFAULT SYSDATE CONSTRAINT "FECHA_DEL_CLICK_NN" NOT NULL ENABLE, 
	 CONSTRAINT "PK_CLICK" PRIMARY KEY ("ID_CLICK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_CLICK" 
  BEFORE INSERT ON click
  FOR EACH ROW
BEGIN
  :new.id_click := click_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_CLICK" ENABLE;
 

  CREATE TABLE "BDWEB"."COLOR_DE_OJOS" 
   (	"ID_COLOR_OJOS" NUMBER(6,0), 
	"COLOR" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_COLOR_OJOS" PRIMARY KEY ("ID_COLOR_OJOS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_OJOS" 
  BEFORE INSERT ON color_de_ojos
  FOR EACH ROW
BEGIN
  :new.id_color_ojos := color_ojos_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_OJOS" ENABLE;
 

  CREATE TABLE "BDWEB"."COLOR_DE_PELO" 
   (	"ID_COLOR_PELO" NUMBER(6,0), 
	"COLOR" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_COLOR_PELO" PRIMARY KEY ("ID_COLOR_PELO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_PELO" 
  BEFORE INSERT ON color_de_pelo
  FOR EACH ROW
BEGIN
  :new.id_color_pelo := color_pelo_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_PELO" ENABLE;
 

  CREATE TABLE "BDWEB"."COLOR_DE_PIEL" 
   (	"ID_COLOR_PIEL" NUMBER(6,0), 
	"COLOR" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_COLOR_PIEL" PRIMARY KEY ("ID_COLOR_PIEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_PIEL" 
  BEFORE INSERT ON color_de_piel
  FOR EACH ROW
BEGIN
  :new.id_color_piel := color_piel_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_PIEL" ENABLE;
 

  CREATE TABLE "BDWEB"."DEPORTES" 
   (	"ID_DEPORTE" NUMBER(6,0), 
	"TIPO_DEPORTE" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_DEPORTES" PRIMARY KEY ("ID_DEPORTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_DEPORTES" 
  BEFORE INSERT ON deportes
  FOR EACH ROW
BEGIN
  :new.id_deporte := deportes_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_DEPORTES" ENABLE;
 

  CREATE TABLE "BDWEB"."ESTADO_CIVIL" 
   (	"ID_ESTADO_CIVIL" NUMBER(6,0), 
	"ESTADO_CIVIL_ACTUAL" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_ESTADO_CIVIL" PRIMARY KEY ("ID_ESTADO_CIVIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_ESTADO" 
  BEFORE INSERT ON estado_civil
  FOR EACH ROW
BEGIN
  :new.id_estado_civil := estado_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_ESTADO" ENABLE;
 

  CREATE TABLE "BDWEB"."EVENTOS" 
   (	"ID_EVENTOS" NUMBER(6,0), 
	"NOMBRE_DEL_EVENTO" VARCHAR2(20 BYTE), 
	"LUGAR_DEL_EVENTO" VARCHAR2(20 BYTE), 
	"ID_FECHA_DE_EVENTO" NUMBER(6,0), 
	 CONSTRAINT "PK_EVENTOS" PRIMARY KEY ("ID_EVENTOS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA"  ENABLE, 
	 CONSTRAINT "FK_FECHA_DE_EVENTOS" FOREIGN KEY ("ID_FECHA_DE_EVENTO")
	  REFERENCES "BDWEB"."FECHA_DE_EVENTO" ("ID_FECHA_DE_EVENTO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_EVENTOS" 
  BEFORE INSERT ON eventos
  FOR EACH ROW
BEGIN
  :new.id_eventos := estado_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_EVENTOS" ENABLE;
 

  CREATE TABLE "BDWEB"."FECHA_DE_EVENTO" 
   (	"ID_FECHA_DE_EVENTO" NUMBER(6,0), 
	"FECHA_EVENTO" DATE DEFAULT SYSDATE CONSTRAINT "FECHA_EVENTO_NN" NOT NULL ENABLE, 
	 CONSTRAINT "PK_FECHA_DE_EVETO" PRIMARY KEY ("ID_FECHA_DE_EVENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_FECHA_EVENTOS" 
  BEFORE INSERT ON fecha_de_evento
  FOR EACH ROW
BEGIN
  :new.id_fecha_de_evento := fecha_evento_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_FECHA_EVENTOS" ENABLE;
 

  CREATE TABLE "BDWEB"."FECHA_DE_NACIMIENTO" 
   (	"ID_FECHA_DE_NACIMIENTO" NUMBER(6,0), 
	"NACIMIENTO" DATE DEFAULT SYSDATE CONSTRAINT "FECHA_DE_NACIMIENTO_NN" NOT NULL ENABLE, 
	 CONSTRAINT "PK_FECHA_DE_NACIMIENTO" PRIMARY KEY ("ID_FECHA_DE_NACIMIENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_NACIMIENTO" 
  BEFORE INSERT ON fecha_de_nacimiento
  FOR EACH ROW
BEGIN
  :new.id_fecha_de_nacimiento := nacimiento_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_NACIMIENTO" ENABLE;
 

  CREATE TABLE "BDWEB"."FOTO" 
   (	"ID_FOTO" NUMBER(6,0), 
	"SUBIR_FOTO" BLOB, 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"ID_PERSONA" NUMBER(6,0), 
	"TIPO" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_FOTO" PRIMARY KEY ("ID_FOTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA"  ENABLE, 
	 CONSTRAINT "FK_PERSONA_FOTO" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES "BDWEB"."PERSONA" ("ID_PERSONA") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" 
 LOB ("SUBIR_FOTO") STORE AS BASICFILE (
  TABLESPACE "BDWEB_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
 

  CREATE TABLE "BDWEB"."FRECUENCIA_EJERCICIO" 
   (	"ID_FRECUENCIA" NUMBER(6,0), 
	"CANTIDAD" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_FRECUENCIA_EJERCICIO" PRIMARY KEY ("ID_FRECUENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_FRECUENCIA" 
  BEFORE INSERT ON frecuencia_ejercicio
  FOR EACH ROW
BEGIN
  :new.id_frecuencia := ejercicio_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_FRECUENCIA" ENABLE;
 

  CREATE TABLE "BDWEB"."GENERO" 
   (	"ID_GENERO" NUMBER(6,0), 
	"GENERO_PERSONA" VARCHAR2(20 BYTE) CONSTRAINT "GENERO_VAR" NOT NULL ENABLE, 
	 CONSTRAINT "PK_GENERO" PRIMARY KEY ("ID_GENERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_GENERO" 
  BEFORE INSERT ON genero
  FOR EACH ROW
BEGIN
  :new.id_genero := genero_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_GENERO" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_CUERPO " 
  BEFORE INSERT ON genero
  FOR EACH ROW
BEGIN
  :new.id_TIPO_DE_CUERPO := CUERPO_seq.nextval;
END;
 

/
ALTER TRIGGER "BDWEB"."TRIGGER_CUERPO " ENABLE;
 

  CREATE TABLE "BDWEB"."HOBBY" 
   (	"ID_HOBBY" NUMBER(6,0), 
	"ACTIVIDAD_HOBBY" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_HOBBY" PRIMARY KEY ("ID_HOBBY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_HOBBY" 
  BEFORE INSERT ON hobby
  FOR EACH ROW
BEGIN
  :new.id_hobby := hobby_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_HOBBY" ENABLE;
 

  CREATE TABLE "BDWEB"."IDIOMA" 
   (	"ID_IDIOMA" NUMBER(6,0), 
	"NOMBRE_IDIOMA" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_IDIOMA" PRIMARY KEY ("ID_IDIOMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_IDIOMA" 
  BEFORE INSERT ON idioma
  FOR EACH ROW
BEGIN
  :new.id_idioma := idioma_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_IDIOMA" ENABLE;
 

  CREATE TABLE "BDWEB"."INTENCION" 
   (	"ID_INTENCION" NUMBER(6,0), 
	"TIPO_DE_INTENCION" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_INTENCION" PRIMARY KEY ("ID_INTENCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_INTENCION" 
  BEFORE INSERT ON intencion
  FOR EACH ROW
BEGIN
  :new.id_intencion := intencion_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_INTENCION" ENABLE;
 

  CREATE TABLE "BDWEB"."INTERESES" 
   (	"ID_INTERESES" NUMBER(6,0), 
	"TIPO_INTERESES" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_INTERESES" PRIMARY KEY ("ID_INTERESES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_INTERESES" 
  BEFORE INSERT ON intereses
  FOR EACH ROW
BEGIN
  :new.id_intereses := intereses_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_INTERESES" ENABLE;
 

  CREATE TABLE "BDWEB"."MATCH_CONTAINER" 
   (	"ID_PERSONA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE TABLE "BDWEB"."MATCH_POSITIVO" 
   (	"ID_POSITIVO_MATCH" NUMBER(6,0), 
	"ID_MATCHER" NUMBER(6,0), 
	"ID_MATCHEE" NUMBER(6,0), 
	 CONSTRAINT "PK_MATCH_POSITIVO" PRIMARY KEY ("ID_POSITIVO_MATCH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GE_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GE_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_MATCH" 
  BEFORE INSERT ON match_positivo
  FOR EACH ROW
BEGIN
  :new.id_positivo_match := match_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_MATCH" ENABLE;
 

  CREATE TABLE "BDWEB"."NIVEL_DE_EDUCACION" 
   (	"ID_NIVEL_DE_EDUCACION" NUMBER(6,0), 
	"NIVEL_EDUCACION" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_NIVEL_DE_EDUCACION" PRIMARY KEY ("ID_NIVEL_DE_EDUCACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_EDUCACION" 
  BEFORE INSERT ON nivel_de_educacion
  FOR EACH ROW
BEGIN
  :new.id_nivel_de_educacion := educacion_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_EDUCACION" ENABLE;
 

  CREATE TABLE "BDWEB"."NO_MATCH" 
   (	"ID_NEGATIVO_MATCH" NUMBER(6,0), 
	"ID_NO_MATCHER" NUMBER(6,0), 
	"ID_NO_MATCHEE" NUMBER(6,0), 
	 CONSTRAINT "PK_NO_MATCH" PRIMARY KEY ("ID_NEGATIVO_MATCH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GE_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GE_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_NO_MATCH" 
  BEFORE INSERT ON no_match
  FOR EACH ROW
BEGIN
  :new.id_negativo_match := no_match_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_NO_MATCH" ENABLE;
 

  CREATE TABLE "BDWEB"."OCUPACION" 
   (	"ID_OCUPACION" NUMBER(6,0), 
	"OCUPACION" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_OCUPACION" PRIMARY KEY ("ID_OCUPACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_OCUPACION" 
  BEFORE INSERT ON ocupacion
  FOR EACH ROW
BEGIN
  :new.id_ocupacion := ocupacion_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_OCUPACION" ENABLE;
 

  CREATE TABLE "BDWEB"."PAIS" 
   (	"ID_PAIS" NUMBER(6,0), 
	"NOMBRE_PAIS" VARCHAR2(20 BYTE) CONSTRAINT "PAIS_VAR" NOT NULL ENABLE, 
	 CONSTRAINT "PK_PAIS" PRIMARY KEY ("ID_PAIS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_PAIS" 
  BEFORE INSERT ON pais
  FOR EACH ROW
BEGIN
  :new.id_pais := pais_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_PAIS" ENABLE;
 

  CREATE TABLE "BDWEB"."PAREJA" 
   (	"ID_PERSONA" NUMBER(6,0), 
	"FUMADOR" VARCHAR2(3 BYTE), 
	"TIENE_MASCOTA" VARCHAR2(3 BYTE), 
	"TIENE_HIJOS" VARCHAR2(3 BYTE), 
	"ID_BEBEDOR" NUMBER(6,0), 
	"ID_INTENCION" NUMBER(6,0), 
	"ID_RANGO_DE_EDAD" NUMBER(6,0), 
	"ID_RANGO_SALARIAL" NUMBER(6,0), 
	"ID_TENGO_HIJOS" NUMBER(6,0), 
	"ID_TIPO_DE_CUERPO" NUMBER(6,0), 
	"ID_PAREJA" NUMBER(6,0), 
	"ID_GENERO" NUMBER(6,0), 
	 CONSTRAINT "PK_PAREJA" PRIMARY KEY ("ID_PERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA"  ENABLE, 
	 CONSTRAINT "FK_BEBEDOR_PAREJA" FOREIGN KEY ("ID_BEBEDOR")
	  REFERENCES "BDWEB"."BEBEDOR" ("ID_BEBEDOR") ENABLE, 
	 CONSTRAINT "FK_INTENCION_PAREJA" FOREIGN KEY ("ID_INTENCION")
	  REFERENCES "BDWEB"."INTENCION" ("ID_INTENCION") ENABLE, 
	 CONSTRAINT "FK_RANGO_DE_EDAD_PAREJA" FOREIGN KEY ("ID_RANGO_DE_EDAD")
	  REFERENCES "BDWEB"."RANGO_DE_EDAD" ("ID_RANGO_DE_EDAD") ENABLE, 
	 CONSTRAINT "FK_TENGO_HIJOS_PAREJA" FOREIGN KEY ("ID_TENGO_HIJOS")
	  REFERENCES "BDWEB"."TENGO_HIJOS" ("ID_TENGO_HIJOS") ENABLE, 
	 CONSTRAINT "FK_TIPO_DE_CUERPO_PAREJA" FOREIGN KEY ("ID_TIPO_DE_CUERPO")
	  REFERENCES "BDWEB"."TIPO_DE_CUERPO" ("ID_TIPO_DE_CUERPO") ENABLE, 
	 CONSTRAINT "FK_PAREJA_PERSONA" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES "BDWEB"."PERSONA" ("ID_PERSONA") ENABLE, 
	 CONSTRAINT "PAREJA_GENERO_FK1" FOREIGN KEY ("ID_GENERO")
	  REFERENCES "BDWEB"."GENERO" ("ID_GENERO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_PAREJA" 
  BEFORE INSERT ON pareja
  FOR EACH ROW
BEGIN
  :new.id_pareja := pareja_seq.nextval;
END;

/
ALTER TRIGGER "BDWEB"."TRIGGER_PAREJA" ENABLE;
 

  CREATE TABLE "BDWEB"."PAREJAXDEPORTE" 
   (	"ID_PAREJA" NUMBER(6,0), 
	"ID_DEPORTE" NUMBER(6,0), 
	 CONSTRAINT "PK_PAREJA_DEPORTE" PRIMARY KEY ("ID_PAREJA", "ID_DEPORTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA"  ENABLE, 
	 CONSTRAINT "FK_PAREJA_DEPORTES" FOREIGN KEY ("ID_PAREJA")
	  REFERENCES "BDWEB"."PAREJA" ("ID_PERSONA") ENABLE, 
	 CONSTRAINT "FK_DEPORTE_PAREJA" FOREIGN KEY ("ID_DEPORTE")
	  REFERENCES "BDWEB"."DEPORTES" ("ID_DEPORTE") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE TABLE "BDWEB"."PAREJAXHOBBY" 
   (	"ID_PAREJA" NUMBER(6,0), 
	"ID_HOBBY" NUMBER(6,0), 
	 CONSTRAINT "PK_PAREJA_HOBBY" PRIMARY KEY ("ID_PAREJA", "ID_HOBBY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA"  ENABLE, 
	 CONSTRAINT "FK_PAREJA_HOBBY" FOREIGN KEY ("ID_PAREJA")
	  REFERENCES "BDWEB"."PAREJA" ("ID_PERSONA") ENABLE, 
	 CONSTRAINT "FK_HOBBY_PAREJA" FOREIGN KEY ("ID_HOBBY")
	  REFERENCES "BDWEB"."HOBBY" ("ID_HOBBY") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE TABLE "BDWEB"."PAREJAXIDIOMA" 
   (	"ID_IDIOMA" NUMBER(6,0), 
	"ID_PAREJA" NUMBER(6,0), 
	 CONSTRAINT "FK_IDIOMA_PAREJA" FOREIGN KEY ("ID_IDIOMA")
	  REFERENCES "BDWEB"."IDIOMA" ("ID_IDIOMA") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE TABLE "BDWEB"."PAREJAXINTERESES" 
   (	"ID_PAREJA" NUMBER(6,0), 
	"ID_INTERESES" NUMBER(6,0), 
	 CONSTRAINT "PK_PAREJA_INTERESES" PRIMARY KEY ("ID_PAREJA", "ID_INTERESES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA"  ENABLE, 
	 CONSTRAINT "FK_PAREJA_INTERESES" FOREIGN KEY ("ID_PAREJA")
	  REFERENCES "BDWEB"."PAREJA" ("ID_PERSONA") ENABLE, 
	 CONSTRAINT "FK_INTERESES_PAREJA" FOREIGN KEY ("ID_INTERESES")
	  REFERENCES "BDWEB"."INTERESES" ("ID_INTERESES") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE TABLE "BDWEB"."PERSONA" 
   (	"ID_PERSONA" NUMBER(6,0), 
	"NOMBRE" VARCHAR2(20 BYTE) CONSTRAINT "NOMBRE_VAR" NOT NULL ENABLE, 
	"APELLIDO" VARCHAR2(20 BYTE) CONSTRAINT "APELLIDO_VAR" NOT NULL ENABLE, 
	"FUMADOR" VARCHAR2(3 BYTE), 
	"TIENE_MASCOTA" VARCHAR2(40 BYTE), 
	"FRASE_IDENTIFICADORA" VARCHAR2(1000 BYTE) CONSTRAINT "FRASE_IDENTIFICADORA_VAR" NOT NULL ENABLE, 
	"APODO" VARCHAR2(20 BYTE) CONSTRAINT "APODO_VAR" NOT NULL ENABLE, 
	"CANTIDAD_DE_HIJOS" NUMBER(6,0), 
	"ID_ALTURA" NUMBER(6,0), 
	"ID_BEBEDOR" NUMBER(6,0), 
	"ID_CIUDAD" NUMBER(6,0), 
	"ID_COLOR_OJOS" NUMBER(6,0), 
	"ID_COLOR_PELO" NUMBER(6,0), 
	"ID_COLOR_PIEL" NUMBER(6,0), 
	"ID_ESTADO_CIVIL" NUMBER(6,0), 
	"ID_FECHA_DE_NACIMIENTO" NUMBER(6,0), 
	"ID_FRECUENCIA" NUMBER(6,0), 
	"ID_INTENCION" NUMBER(6,0), 
	"ID_NIVEL_DE_EDUCACION" NUMBER(6,0), 
	"ID_OCUPACION" NUMBER(6,0), 
	"ID_PESO" NUMBER(6,0), 
	"ID_TIPO_DE_CUERPO" NUMBER(6,0), 
	"ID_RELIGION" NUMBER(6,0), 
	"ID_RANGO_SALARIAL" NUMBER(6,0), 
	"ID_TENGO_HIJOS" NUMBER(6,0), 
	"ID_ZODIACAL" NUMBER(6,0), 
	"GENERO" VARCHAR2(20 BYTE), 
	"PASS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PERSONA" PRIMARY KEY ("ID_PERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE, 
	 CONSTRAINT "FK_ALTURA" FOREIGN KEY ("ID_ALTURA")
	  REFERENCES "BDWEB"."ALTURA" ("ID_ALTURA") ENABLE, 
	 CONSTRAINT "FK_BEBEDOR" FOREIGN KEY ("ID_BEBEDOR")
	  REFERENCES "BDWEB"."BEBEDOR" ("ID_BEBEDOR") ENABLE, 
	 CONSTRAINT "FK_CIUDAD" FOREIGN KEY ("ID_CIUDAD")
	  REFERENCES "BDWEB"."CIUDAD" ("ID_CIUDAD") ENABLE, 
	 CONSTRAINT "FK_COLOR_OJOS" FOREIGN KEY ("ID_COLOR_OJOS")
	  REFERENCES "BDWEB"."COLOR_DE_OJOS" ("ID_COLOR_OJOS") ENABLE, 
	 CONSTRAINT "FK_COLOR_PELO" FOREIGN KEY ("ID_COLOR_PELO")
	  REFERENCES "BDWEB"."COLOR_DE_PELO" ("ID_COLOR_PELO") ENABLE, 
	 CONSTRAINT "FK_COLOR_PIEL" FOREIGN KEY ("ID_COLOR_PIEL")
	  REFERENCES "BDWEB"."COLOR_DE_PIEL" ("ID_COLOR_PIEL") ENABLE, 
	 CONSTRAINT "FK_ESTADO_CIVIL" FOREIGN KEY ("ID_ESTADO_CIVIL")
	  REFERENCES "BDWEB"."ESTADO_CIVIL" ("ID_ESTADO_CIVIL") ENABLE, 
	 CONSTRAINT "FK_FECHA_DE_NACIMIENTO" FOREIGN KEY ("ID_FECHA_DE_NACIMIENTO")
	  REFERENCES "BDWEB"."FECHA_DE_NACIMIENTO" ("ID_FECHA_DE_NACIMIENTO") ENABLE, 
	 CONSTRAINT "FK_FRECUENCIA" FOREIGN KEY ("ID_FRECUENCIA")
	  REFERENCES "BDWEB"."FRECUENCIA_EJERCICIO" ("ID_FRECUENCIA") ENABLE, 
	 CONSTRAINT "FK_INTENCION" FOREIGN KEY ("ID_INTENCION")
	  REFERENCES "BDWEB"."INTENCION" ("ID_INTENCION") ENABLE, 
	 CONSTRAINT "FK_NIVEL_DE_EDUCACION" FOREIGN KEY ("ID_NIVEL_DE_EDUCACION")
	  REFERENCES "BDWEB"."NIVEL_DE_EDUCACION" ("ID_NIVEL_DE_EDUCACION") ENABLE, 
	 CONSTRAINT "FK_OCUPACION" FOREIGN KEY ("ID_OCUPACION")
	  REFERENCES "BDWEB"."OCUPACION" ("ID_OCUPACION") ENABLE, 
	 CONSTRAINT "FK_PESO" FOREIGN KEY ("ID_PESO")
	  REFERENCES "BDWEB"."PESO" ("ID_PESO") ENABLE, 
	 CONSTRAINT "FK_TIPO_DE_CUERPO" FOREIGN KEY ("ID_TIPO_DE_CUERPO")
	  REFERENCES "BDWEB"."TIPO_DE_CUERPO" ("ID_TIPO_DE_CUERPO") ENABLE, 
	 CONSTRAINT "FK_RELIGION" FOREIGN KEY ("ID_RELIGION")
	  REFERENCES "BDWEB"."RELIGION" ("ID_RELIGION") ENABLE, 
	 CONSTRAINT "FK_RANGO_SALARIAL" FOREIGN KEY ("ID_RANGO_SALARIAL")
	  REFERENCES "BDWEB"."RANGO_SALARIAL" ("ID_RANGO_SALARIO") ENABLE, 
	 CONSTRAINT "FK_TENGO_HIJOS" FOREIGN KEY ("ID_TENGO_HIJOS")
	  REFERENCES "BDWEB"."TENGO_HIJOS" ("ID_TENGO_HIJOS") ENABLE, 
	 CONSTRAINT "FK_ZODIACAL" FOREIGN KEY ("ID_ZODIACAL")
	  REFERENCES "BDWEB"."ZODIACAL" ("ID_SIGNO_ZODIACAL") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_PERSONA" 
  BEFORE INSERT ON persona
  FOR EACH ROW
BEGIN
  :new.id_persona := persona_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_PERSONA" ENABLE;
 

  CREATE TABLE "BDWEB"."PERSONAXCLICKS" 
   (	"ID_PERSONA" NUMBER(6,0), 
	"ID_CLICKS" NUMBER(6,0), 
	 CONSTRAINT "PK_PERSONA_CLICKS" PRIMARY KEY ("ID_PERSONA", "ID_CLICKS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA"  ENABLE, 
	 CONSTRAINT "FK_PERSONA" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES "BDWEB"."PERSONA" ("ID_PERSONA") ENABLE, 
	 CONSTRAINT "FK_CLICKS" FOREIGN KEY ("ID_CLICKS")
	  REFERENCES "BDWEB"."CLICK" ("ID_CLICK") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE TABLE "BDWEB"."PERSONAXDEPORTE" 
   (	"ID_PERSONA" NUMBER(6,0), 
	"ID_DEPORTE" NUMBER(6,0), 
	 CONSTRAINT "PK_PERSONA_DEPORTES" PRIMARY KEY ("ID_PERSONA", "ID_DEPORTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA"  ENABLE, 
	 CONSTRAINT "FK_PERSONA_DEPORTE" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES "BDWEB"."PERSONA" ("ID_PERSONA") ENABLE, 
	 CONSTRAINT "FK_DEPORTE" FOREIGN KEY ("ID_DEPORTE")
	  REFERENCES "BDWEB"."DEPORTES" ("ID_DEPORTE") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE TABLE "BDWEB"."PERSONAXEVENTOS" 
   (	"ID_PERSONA" NUMBER(6,0), 
	"ID_EVENTOS" NUMBER(6,0), 
	 CONSTRAINT "PK_PERSONA_EVENTOS" PRIMARY KEY ("ID_PERSONA", "ID_EVENTOS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA"  ENABLE, 
	 CONSTRAINT "FK_PERSONA_EVENTOS" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES "BDWEB"."PERSONA" ("ID_PERSONA") ENABLE, 
	 CONSTRAINT "FK_EVENTOS" FOREIGN KEY ("ID_EVENTOS")
	  REFERENCES "BDWEB"."EVENTOS" ("ID_EVENTOS") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE TABLE "BDWEB"."PERSONAXHOBBY" 
   (	"ID_PERSONA" NUMBER(6,0), 
	"ID_HOBBY" NUMBER(6,0), 
	 CONSTRAINT "PK_PERSONA_HOBBY" PRIMARY KEY ("ID_PERSONA", "ID_HOBBY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA"  ENABLE, 
	 CONSTRAINT "FK_PERSONA_HOBBY" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES "BDWEB"."PERSONA" ("ID_PERSONA") ENABLE, 
	 CONSTRAINT "FK_HOBBY" FOREIGN KEY ("ID_HOBBY")
	  REFERENCES "BDWEB"."HOBBY" ("ID_HOBBY") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE TABLE "BDWEB"."PERSONAXIDIOMA" 
   (	"ID_PERSONA" NUMBER(6,0), 
	"ID_IDIOMA" NUMBER(6,0), 
	 CONSTRAINT "PK_PERSONA_IDIOMA" PRIMARY KEY ("ID_PERSONA", "ID_IDIOMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA"  ENABLE, 
	 CONSTRAINT "FK_PERSONA_IDIOMA" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES "BDWEB"."PERSONA" ("ID_PERSONA") ENABLE, 
	 CONSTRAINT "FK_IDIOMA" FOREIGN KEY ("ID_IDIOMA")
	  REFERENCES "BDWEB"."IDIOMA" ("ID_IDIOMA") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE TABLE "BDWEB"."PERSONAXINTERESES" 
   (	"ID_PERSONA" NUMBER(6,0), 
	"ID_INTERESES" NUMBER(6,0), 
	 CONSTRAINT "PK_PERSONA_INTERESES" PRIMARY KEY ("ID_PERSONA", "ID_INTERESES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA"  ENABLE, 
	 CONSTRAINT "FK_PERSONA_INTERESES" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES "BDWEB"."PERSONA" ("ID_PERSONA") ENABLE, 
	 CONSTRAINT "FK_INTERESES" FOREIGN KEY ("ID_INTERESES")
	  REFERENCES "BDWEB"."INTERESES" ("ID_INTERESES") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE TABLE "BDWEB"."PERSONAXMATCH" 
   (	"ID_PERSONA" NUMBER(6,0), 
	"ID_MATCH" NUMBER(6,0), 
	 CONSTRAINT "PK_PERSONA_MATCH" PRIMARY KEY ("ID_PERSONA", "ID_MATCH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA"  ENABLE, 
	 CONSTRAINT "FK_PERSONA_MATCH" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES "BDWEB"."PERSONA" ("ID_PERSONA") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE TABLE "BDWEB"."PERSONAXNO_MATCH" 
   (	"ID_PERSONA" NUMBER(6,0), 
	"ID_NO_MATCH" NUMBER(6,0), 
	 CONSTRAINT "PK_PERSONA_NO_MATCH" PRIMARY KEY ("ID_PERSONA", "ID_NO_MATCH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE TABLE "BDWEB"."PERSONAXWINKS" 
   (	"ID_PERSONA" NUMBER(6,0), 
	"ID_WINKS" NUMBER(6,0), 
	 CONSTRAINT "PK_PERSONA_WINKS" PRIMARY KEY ("ID_PERSONA", "ID_WINKS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA"  ENABLE, 
	 CONSTRAINT "FK_PERSONA_WINKS" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES "BDWEB"."PERSONA" ("ID_PERSONA") ENABLE, 
	 CONSTRAINT "FK_WINKS" FOREIGN KEY ("ID_WINKS")
	  REFERENCES "BDWEB"."WINKS" ("ID_WINKS") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE TABLE "BDWEB"."PESO" 
   (	"ID_PESO" NUMBER(6,0), 
	"KILOGRAMOS" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_PESO" PRIMARY KEY ("ID_PESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_PESO" 
  BEFORE INSERT ON peso
  FOR EACH ROW
BEGIN
  :new.id_peso := peso_seq.nextval;
END;

/
ALTER TRIGGER "BDWEB"."TRIGGER_PESO" ENABLE;
 

  CREATE TABLE "BDWEB"."RANGO_DE_EDAD" 
   (	"ID_RANGO_DE_EDAD" NUMBER(6,0), 
	"PISO" NUMBER(6,0), 
	"TECHO" NUMBER(6,0), 
	 CONSTRAINT "PK_RANGO_EDAD" PRIMARY KEY ("ID_RANGO_DE_EDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE, 
	 CONSTRAINT "RANGO_DE_EDAD_CHK1" CHECK (
TECHO >= PISO
) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_RANGO" 
  BEFORE INSERT ON rango_de_edad
  FOR EACH ROW
BEGIN
  :new.id_rango_de_edad := rango_seq.nextval;
END;

/
ALTER TRIGGER "BDWEB"."TRIGGER_RANGO" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_RANGO_EDAD" 
  BEFORE INSERT ON rango_de_edad
  FOR EACH ROW
BEGIN
  :new.id_rango_de_edad := rango_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_RANGO_EDAD" ENABLE;
 

  CREATE TABLE "BDWEB"."RANGO_SALARIAL" 
   (	"ID_RANGO_SALARIO" NUMBER(6,0), 
	"SALARIO" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_RANGO_SALARIAL" PRIMARY KEY ("ID_RANGO_SALARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_SALARIAL" 
  BEFORE INSERT ON rango_salarial
  FOR EACH ROW
BEGIN
  :new.id_rango_salario := salarial_seq.nextval;
END;

/
ALTER TRIGGER "BDWEB"."TRIGGER_SALARIAL" ENABLE;
 

  CREATE TABLE "BDWEB"."RELIGION" 
   (	"ID_RELIGION" NUMBER(6,0), 
	"NOMBRE_RELIGION" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_RELIGION" PRIMARY KEY ("ID_RELIGION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_RELIGION" 
  BEFORE INSERT ON religion
  FOR EACH ROW
BEGIN
  :new.id_religion := religion_seq.nextval;
END;

/
ALTER TRIGGER "BDWEB"."TRIGGER_RELIGION" ENABLE;
 

  CREATE TABLE "BDWEB"."TENGO_HIJOS" 
   (	"ID_TENGO_HIJOS" NUMBER(6,0), 
	"OPINION_HIJOS" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_TENER_HIJOS" PRIMARY KEY ("ID_TENGO_HIJOS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_HIJOS" 
  BEFORE INSERT ON tengo_hijos
  FOR EACH ROW
BEGIN
  :new.id_tengo_hijos := hijos_seq.nextval;
END;

/
ALTER TRIGGER "BDWEB"."TRIGGER_HIJOS" ENABLE;
 

  CREATE TABLE "BDWEB"."TIPO_DE_CUERPO" 
   (	"ID_TIPO_DE_CUERPO" NUMBER(6,0), 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_TIPO_DE_CUERPO" PRIMARY KEY ("ID_TIPO_DE_CUERPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_TIPO_CUERPO " 
  BEFORE INSERT ON tipo_de_cuerpo
  FOR EACH ROW
BEGIN
  :new.id_TIPO_DE_CUERPO := CUERPO_seq.nextval;
END;
 

/
ALTER TRIGGER "BDWEB"."TRIGGER_TIPO_CUERPO " ENABLE;
 

  CREATE TABLE "BDWEB"."WINKS" 
   (	"ID_WINKS" NUMBER(6,0), 
	"ID_WINKER" NUMBER(6,0), 
	"ID_WINKED" NUMBER(6,0), 
	"FECHA_DEL_WINK" DATE DEFAULT SYSDATE CONSTRAINT "FECHA_DEL_WINK_NN" NOT NULL ENABLE, 
	 CONSTRAINT "PK_WINKS" PRIMARY KEY ("ID_WINKS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_WINKS" 
  BEFORE INSERT ON winks
  FOR EACH ROW
BEGIN
  :new.id_winks := winks_seq.nextval;
END;

/
ALTER TRIGGER "BDWEB"."TRIGGER_WINKS" ENABLE;
 

  CREATE TABLE "BDWEB"."ZODIACAL" 
   (	"ID_SIGNO_ZODIACAL" NUMBER(6,0), 
	"SIGNO" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_ZODIACAL" PRIMARY KEY ("ID_SIGNO_ZODIACAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDWEB_DATA" ;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_ZODIACAL" 
  BEFORE INSERT ON zodiacal
  FOR EACH ROW
BEGIN
  :new.id_signo_zodiacal := zodiacal_seq.nextval;
END;

/
ALTER TRIGGER "BDWEB"."TRIGGER_ZODIACAL" ENABLE;
 
