
  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_ALTURA" 
  BEFORE INSERT ON altura
  FOR EACH ROW
BEGIN
  :new.id_altura := altura_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_ALTURA" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_BEBEDOR" 
  BEFORE INSERT ON bebedor
  FOR EACH ROW
BEGIN
  :new.id_bebedor := bebedor_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_BEBEDOR" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_CIUDAD" 
  BEFORE INSERT ON ciudad
  FOR EACH ROW
BEGIN
  :new.id_ciudad := ciudad_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_CIUDAD" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_CLICK" 
  BEFORE INSERT ON click
  FOR EACH ROW
BEGIN
  :new.id_click := click_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_CLICK" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_CUERPO " 
  BEFORE INSERT ON genero
  FOR EACH ROW
BEGIN
  :new.id_TIPO_DE_CUERPO := CUERPO_seq.nextval;
END;
 

/
ALTER TRIGGER "BDWEB"."TRIGGER_CUERPO " ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_DEPORTES" 
  BEFORE INSERT ON deportes
  FOR EACH ROW
BEGIN
  :new.id_deporte := deportes_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_DEPORTES" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_EDUCACION" 
  BEFORE INSERT ON nivel_de_educacion
  FOR EACH ROW
BEGIN
  :new.id_nivel_de_educacion := educacion_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_EDUCACION" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_ESTADO" 
  BEFORE INSERT ON estado_civil
  FOR EACH ROW
BEGIN
  :new.id_estado_civil := estado_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_ESTADO" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_EVENTOS" 
  BEFORE INSERT ON eventos
  FOR EACH ROW
BEGIN
  :new.id_eventos := estado_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_EVENTOS" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_FECHA_EVENTOS" 
  BEFORE INSERT ON fecha_de_evento
  FOR EACH ROW
BEGIN
  :new.id_fecha_de_evento := fecha_evento_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_FECHA_EVENTOS" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_FRECUENCIA" 
  BEFORE INSERT ON frecuencia_ejercicio
  FOR EACH ROW
BEGIN
  :new.id_frecuencia := ejercicio_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_FRECUENCIA" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_GENERO" 
  BEFORE INSERT ON genero
  FOR EACH ROW
BEGIN
  :new.id_genero := genero_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_GENERO" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_HIJOS" 
  BEFORE INSERT ON tengo_hijos
  FOR EACH ROW
BEGIN
  :new.id_tengo_hijos := hijos_seq.nextval;
END;

/
ALTER TRIGGER "BDWEB"."TRIGGER_HIJOS" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_HOBBY" 
  BEFORE INSERT ON hobby
  FOR EACH ROW
BEGIN
  :new.id_hobby := hobby_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_HOBBY" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_IDIOMA" 
  BEFORE INSERT ON idioma
  FOR EACH ROW
BEGIN
  :new.id_idioma := idioma_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_IDIOMA" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_INTENCION" 
  BEFORE INSERT ON intencion
  FOR EACH ROW
BEGIN
  :new.id_intencion := intencion_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_INTENCION" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_INTERESES" 
  BEFORE INSERT ON intereses
  FOR EACH ROW
BEGIN
  :new.id_intereses := intereses_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_INTERESES" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_MATCH" 
  BEFORE INSERT ON match_positivo
  FOR EACH ROW
BEGIN
  :new.id_positivo_match := match_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_MATCH" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_NACIMIENTO" 
  BEFORE INSERT ON fecha_de_nacimiento
  FOR EACH ROW
BEGIN
  :new.id_fecha_de_nacimiento := nacimiento_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_NACIMIENTO" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_NO_MATCH" 
  BEFORE INSERT ON no_match
  FOR EACH ROW
BEGIN
  :new.id_negativo_match := no_match_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_NO_MATCH" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_OCUPACION" 
  BEFORE INSERT ON ocupacion
  FOR EACH ROW
BEGIN
  :new.id_ocupacion := ocupacion_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_OCUPACION" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_OJOS" 
  BEFORE INSERT ON color_de_ojos
  FOR EACH ROW
BEGIN
  :new.id_color_ojos := color_ojos_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_OJOS" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_PAIS" 
  BEFORE INSERT ON pais
  FOR EACH ROW
BEGIN
  :new.id_pais := pais_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_PAIS" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_PAREJA" 
  BEFORE INSERT ON pareja
  FOR EACH ROW
BEGIN
  :new.id_pareja := pareja_seq.nextval;
END;

/
ALTER TRIGGER "BDWEB"."TRIGGER_PAREJA" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_PELO" 
  BEFORE INSERT ON color_de_pelo
  FOR EACH ROW
BEGIN
  :new.id_color_pelo := color_pelo_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_PELO" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_PERSONA" 
  BEFORE INSERT ON persona
  FOR EACH ROW
BEGIN
  :new.id_persona := persona_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_PERSONA" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_PESO" 
  BEFORE INSERT ON peso
  FOR EACH ROW
BEGIN
  :new.id_peso := peso_seq.nextval;
END;

/
ALTER TRIGGER "BDWEB"."TRIGGER_PESO" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_PIEL" 
  BEFORE INSERT ON color_de_piel
  FOR EACH ROW
BEGIN
  :new.id_color_piel := color_piel_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_PIEL" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_RANGO" 
  BEFORE INSERT ON rango_de_edad
  FOR EACH ROW
BEGIN
  :new.id_rango_de_edad := rango_seq.nextval;
END;

/
ALTER TRIGGER "BDWEB"."TRIGGER_RANGO" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_RANGO_EDAD" 
  BEFORE INSERT ON rango_de_edad
  FOR EACH ROW
BEGIN
  :new.id_rango_de_edad := rango_seq.nextval;
END;
/
ALTER TRIGGER "BDWEB"."TRIGGER_RANGO_EDAD" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_RELIGION" 
  BEFORE INSERT ON religion
  FOR EACH ROW
BEGIN
  :new.id_religion := religion_seq.nextval;
END;

/
ALTER TRIGGER "BDWEB"."TRIGGER_RELIGION" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_SALARIAL" 
  BEFORE INSERT ON rango_salarial
  FOR EACH ROW
BEGIN
  :new.id_rango_salario := salarial_seq.nextval;
END;

/
ALTER TRIGGER "BDWEB"."TRIGGER_SALARIAL" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_TIPO_CUERPO " 
  BEFORE INSERT ON tipo_de_cuerpo
  FOR EACH ROW
BEGIN
  :new.id_TIPO_DE_CUERPO := CUERPO_seq.nextval;
END;
 

/
ALTER TRIGGER "BDWEB"."TRIGGER_TIPO_CUERPO " ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_WINKS" 
  BEFORE INSERT ON winks
  FOR EACH ROW
BEGIN
  :new.id_winks := winks_seq.nextval;
END;

/
ALTER TRIGGER "BDWEB"."TRIGGER_WINKS" ENABLE;
 

  CREATE OR REPLACE TRIGGER "BDWEB"."TRIGGER_ZODIACAL" 
  BEFORE INSERT ON zodiacal
  FOR EACH ROW
BEGIN
  :new.id_signo_zodiacal := zodiacal_seq.nextval;
END;

/
ALTER TRIGGER "BDWEB"."TRIGGER_ZODIACAL" ENABLE;
 
